FROM microsoft/dotnet
 
 MAINTAINER gamelinfabien@gmail.com
 
 WORKDIR /app
 
 COPY /Candidate-Management/src/
 RUN dotnet restore
 COPY . .
 RUN dotnet publish -c Release -o Candidate-Management 

 RUN sudo nano /etc/crontab
 
 RUN 00.2,16 * * * /app/Candidate-Management 
 
 ADD /etc/crontab /app/Candidate-Management 
 RUN crontab /app/Candidate-ManagementCandidate-Management/crontab
 ADD files/bin/start-cron.sh /usr/bin/start-cron.sstart-cron.s 
 RUN chmod +x /usr/bin/start-cron.sh
 RUN touch /var/log/cron.log
 
